[site]
title = "Junkai Shao"
description = "MRes Student in Mechanical Engineering."
favicon = "/favicon.svg"
last_updated = "May 2026"

[author]
name = "JunKai Shao"
title = "MRes Student"
institution = "University of Nottingham Ningbo China"
avatar = "/face.png"

[social]
email = "sjunkai0925@163.com"
location = "Ningbo, Zhejiang, China"
location_url = ""
location_details = ["Ningbo, Zhejiang, China"]
google_scholar = ""
orcid = ""
github = "https://github.com/Edwin-Shao"
linkedin = ""
twitter = ""

[features]
enable_likes = false
enable_one_page_mode = false

[i18n]
enabled = true
locales = ["zh", "en"]
default_locale = "en"
mode = "fixed"
fixed_locale = "en"
persist = true
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
