[[news]]
date = "2026 – Present"
content = "MRes in Mechanical Engineering, University of Nottingham Ningbo China (UNNC)"

[[news]]
date = "2026"
content = "Research Intern, Ningbo Institute of Materials Technology and Engineering, Chinese Academy of Sciences (CAS)"

[[news]]
date = "2025 – 2026"
content = "UAV Development Intern, Guokai Yunji (Ningbo) Low-Altitude Economy Development Co., Ltd."

[[news]]
date = "2022 – 2026"
content = "B.E. in Communication Engineering, Zhejiang Wanli University"
