type = "card"
title = "奖项"
description = ""

[[items]]
title = "二等奖 — 浙江省大学生机器人竞赛"
date = "2025"

[[items]]
title = "金/铜奖 — 浙江省大学生工程实践与创新能力大赛"
date = "2024-2025"

[[items]]
title = "三等奖 — 全国大学生数学建模竞赛"
date = "2024"

[[items]]
title = "优秀学生干部 — 浙江万里学院"
date = "2023-2025"

[[items]]
title = "奖学金 — 浙江万里学院"
date = "2023-2025"
